/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX.h"
#include "RX_aliases.h"
#include "TX.h"
#include "TX_aliases.h"
#include "CAN.h"
#include "DEBUG.h"
#include "DEBUG_SPI_UART.h"
#include "DEBUG_PINS.h"
#include "DEBUG_SPI_UART_PVT.h"
#include "DEBUG_PVT.h"
#include "DEBUG_BOOT.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "DEBUG_SCBCLK.h"
#include "DEBUG_tx.h"
#include "DEBUG_tx_aliases.h"
#include "DEBUG_rx.h"
#include "DEBUG_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

