# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Davis Sauer\Documents\PSoC Creator\Husky Robotics\CAN Tester.cydsn\CAN Tester.cyprj
# Date: Wed, 26 May 2021 21:54:28 GMT
#set_units -time ns
create_clock -name {DEBUG_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyExtClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/ext}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {DEBUG_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]


# Component constraints for C:\Users\Davis Sauer\Documents\PSoC Creator\Husky Robotics\CAN Tester.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Davis Sauer\Documents\PSoC Creator\Husky Robotics\CAN Tester.cydsn\CAN Tester.cyprj
# Date: Wed, 26 May 2021 21:54:26 GMT
