/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_CLOCK.h"
#include "DBG_UART.h"
#include "DBG_UART_SPI_UART.h"
#include "DBG_UART_PINS.h"
#include "DBG_UART_SPI_UART_PVT.h"
#include "DBG_UART_PVT.h"
#include "DBG_UART_BOOT.h"
#include "GPS_UART.h"
#include "GPS_UART_SPI_UART.h"
#include "GPS_UART_PINS.h"
#include "GPS_UART_SPI_UART_PVT.h"
#include "GPS_UART_PVT.h"
#include "GPS_UART_BOOT.h"
#include "RXD.h"
#include "RXD_aliases.h"
#include "TXD.h"
#include "TXD_aliases.h"
#include "CAN.h"
#include "DIP1.h"
#include "DIP1_aliases.h"
#include "DIP2.h"
#include "DIP2_aliases.h"
#include "DIP3.h"
#include "DIP3_aliases.h"
#include "DIP4.h"
#include "DIP4_aliases.h"
#include "IMU_I2C.h"
#include "IMU_I2C_I2C.h"
#include "IMU_I2C_PINS.h"
#include "IMU_I2C_I2C_PVT.h"
#include "IMU_I2C_PVT.h"
#include "IMU_I2C_BOOT.h"
#include "IMU_RST.h"
#include "IMU_RST_aliases.h"
#include "ERR.h"
#include "ERR_aliases.h"
#include "DBG.h"
#include "DBG_aliases.h"
#include "BAT_STAT.h"
#include "BAT_STAT_aliases.h"
#include "DBG_UART_SCBCLK.h"
#include "DBG_UART_tx.h"
#include "DBG_UART_tx_aliases.h"
#include "DBG_UART_rx.h"
#include "DBG_UART_rx_aliases.h"
#include "GPS_UART_tx.h"
#include "GPS_UART_tx_aliases.h"
#include "GPS_UART_SCB_IRQ.h"
#include "GPS_UART_rx.h"
#include "GPS_UART_rx_aliases.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "IMU_I2C_SCBCLK.h"
#include "IMU_I2C_sda.h"
#include "IMU_I2C_sda_aliases.h"
#include "IMU_I2C_scl.h"
#include "IMU_I2C_scl_aliases.h"
#include "IMU_I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

